
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Info"].IsString) { throw new SerializationException(); }  Info = _buf["Info"]; }
        { if(!_buf["Classify"].IsNumber) { throw new SerializationException(); }  Classify = _buf["Classify"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
    }

    public static Item DeserializeItem(JSONNode _buf)
    {
        return new Item(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 道具名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 道具描述
    /// </summary>
    public readonly string Info;
    /// <summary>
    /// 道具分类
    /// </summary>
    public readonly int Classify;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly int Type;
   
    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Name:" + Name + ","
        + "Info:" + Info + ","
        + "Classify:" + Classify + ","
        + "Type:" + Type + ","
        + "}";
    }
}

}
