
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.MFramework
{
public partial class TbTest
{
    private readonly System.Collections.Generic.Dictionary<int, Test> _dataMap;
    private readonly System.Collections.Generic.List<Test> _dataList;
    
    public TbTest(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Test>();
        _dataList = new System.Collections.Generic.List<Test>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Test _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Test.DeserializeTest(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Test> DataMap => _dataMap;
    public System.Collections.Generic.List<Test> DataList => _dataList;

    public Test GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Test Get(int key) => _dataMap[key];
    public Test this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

