
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public MFramework.TbTest TbTest {get; }
    public MFramework.TbItem TbItem {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbTest = new MFramework.TbTest(loader("mframework_tbtest"));
        TbItem = new MFramework.TbItem(loader("mframework_tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbTest.ResolveRef(this);
        TbItem.ResolveRef(this);
    }
}

}
